version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.21
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    env_file: .env
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}?serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge